import Head from 'next/head'
import { useState } from 'react'
import Header from '../components/Header'
import Posts from '../components/Posts'
import SignIn from '../components/SignIn'
import SignUp from '../components/SignUp'

export default function Home() {

  const [onSignUp, setOnSignUp] = useState(false)
  const [onSignIn, setOnSignIn] = useState(false)

  const [firstName2, setFirstName2] = useState('')
  const [lastName2, setLastName2] = useState('')
  const [email2, setEmail2] = useState('')
  const [password2, setPassword2] = useState('')


  return (
    <div className=''>
      <Head>
        <title>ATG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>


      <Header firstName2={firstName2} lastName2={lastName2} setOnSignUp={setOnSignUp} onSignUp={onSignUp} onSignIn={onSignIn} setOnSignIn={setOnSignIn} />

      {onSignUp && <SignUp firstName2={firstName2} lastName2={lastName2} email2={email2} password2={password2} setFirstName2={setFirstName2} setLastName2={setLastName2} setEmail2={setEmail2} setPassword2={setPassword2} setOnSignIn={setOnSignIn} setOnSignUp={setOnSignUp} />}

      {onSignIn && <SignIn setFirstName2={setFirstName2} setEmail2={setEmail2} setOnSignUp={setOnSignUp} setOnSignIn={setOnSignIn} />}
      <Posts onSignIn={onSignIn} onSignUp={onSignUp} />

    </div>
  )
}
 